enableGlobalCache: false

nodeLinker: pnp

npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - linux
