nodeLinker: pnp
npmRegistryServer: 'https://registry.npmjs.org'
enableGlobalCache: false
supportedArchitectures:
  {
    os: ['current', 'linux'],
    cpu: ['current', 'x64'],
    libc: ['current', 'glibc', 'musl'],
  }
