/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
export interface SignUpWithUsernameDto {
  username: string;
  password: string;
}
export interface AuthTokenDto {
  accessToken: string;
}
export interface SignInWithUsernameDto {
  username: string;
  password: string;
}
export interface CreateGameRoomDto {
  /**
   * 게임 방 제목
   * @minLength 1
   * @maxLength 50
   */
  title: string;
}
export type GameRoomDtoStatus =
  (typeof GameRoomDtoStatus)[keyof typeof GameRoomDtoStatus];

export const GameRoomDtoStatus = {
  waiting: 'waiting',
  ready: 'ready',
  inProgress: 'inProgress',
  finished: 'finished',
  paused: 'paused',
} as const;
export interface GameRoomDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  hostId: string;
  status: GameRoomDtoStatus;
  title: string;
  maxMembersCount: number;
  currentMembersCount: number;
}
export type GameRoomMemberDtoRole =
  (typeof GameRoomMemberDtoRole)[keyof typeof GameRoomMemberDtoRole];

export const GameRoomMemberDtoRole = {
  host: 'host',
  player: 'player',
} as const;
export interface GameRoomMemberDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
  gameRoomId: string;
  role: GameRoomMemberDtoRole;
  /** 게임방 구성원의 닉네임(계정 닉네임과 동일함) */
  nickname: string;
}
export interface GameRoomMemberCollectionDto {
  data: GameRoomMemberDto[];
}
export interface GameRoomCollectionDto {
  data: GameRoomDto[];
}
/**
 * error code
 */
export type SignUpWithUsernameControllerSignUpWithUsername400Code =
  (typeof SignUpWithUsernameControllerSignUpWithUsername400Code)[keyof typeof SignUpWithUsernameControllerSignUpWithUsername400Code];

export const SignUpWithUsernameControllerSignUpWithUsername400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;
export type SignUpWithUsernameControllerSignUpWithUsername400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignUpWithUsernameControllerSignUpWithUsername400Code;
};
/**
 * error code
 */
export type SignUpWithUsernameControllerSignUpWithUsername409Code =
  (typeof SignUpWithUsernameControllerSignUpWithUsername409Code)[keyof typeof SignUpWithUsernameControllerSignUpWithUsername409Code];

export const SignUpWithUsernameControllerSignUpWithUsername409Code = {
  ACCOUNTUSERNAME_ALREADY_OCCUPIED: 'ACCOUNT.USERNAME_ALREADY_OCCUPIED',
} as const;
export type SignUpWithUsernameControllerSignUpWithUsername409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignUpWithUsernameControllerSignUpWithUsername409Code;
};
/**
 * error code
 */
export type SignInWithUsernameControllerSignInWithUsername400Code =
  (typeof SignInWithUsernameControllerSignInWithUsername400Code)[keyof typeof SignInWithUsernameControllerSignInWithUsername400Code];

export const SignInWithUsernameControllerSignInWithUsername400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;
export type SignInWithUsernameControllerSignInWithUsername400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignInWithUsernameControllerSignInWithUsername400Code;
};
/**
 * error code
 */
export type SignInWithUsernameControllerSignInWithUsername401Code =
  (typeof SignInWithUsernameControllerSignInWithUsername401Code)[keyof typeof SignInWithUsernameControllerSignInWithUsername401Code];

export const SignInWithUsernameControllerSignInWithUsername401Code = {
  AUTHSIGN_IN_INFO_NOT_MATCHED: 'AUTH.SIGN_IN_INFO_NOT_MATCHED',
} as const;
export type SignInWithUsernameControllerSignInWithUsername401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignInWithUsernameControllerSignInWithUsername401Code;
};
/**
 * error code
 */
export type CreateGameRoomControllerCreateGameRoom400Code =
  (typeof CreateGameRoomControllerCreateGameRoom400Code)[keyof typeof CreateGameRoomControllerCreateGameRoom400Code];

export const CreateGameRoomControllerCreateGameRoom400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;
export type CreateGameRoomControllerCreateGameRoom400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateGameRoomControllerCreateGameRoom400Code;
};
/**
 * error code
 */
export type CreateGameRoomControllerCreateGameRoom401Code =
  (typeof CreateGameRoomControllerCreateGameRoom401Code)[keyof typeof CreateGameRoomControllerCreateGameRoom401Code];

export const CreateGameRoomControllerCreateGameRoom401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;
export type CreateGameRoomControllerCreateGameRoom401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateGameRoomControllerCreateGameRoom401Code;
};
/**
 * error code
 */
export type CreateGameRoomControllerCreateGameRoom500Code =
  (typeof CreateGameRoomControllerCreateGameRoom500Code)[keyof typeof CreateGameRoomControllerCreateGameRoom500Code];

export const CreateGameRoomControllerCreateGameRoom500Code = {
  ACCOUNTNOT_FOUND: 'ACCOUNT.NOT_FOUND',
} as const;
export type CreateGameRoomControllerCreateGameRoom500 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateGameRoomControllerCreateGameRoom500Code;
};
export type ListGameRoomsControllerListGameRoomsParams = {
  /**
     *
        정렬 쿼리. 다중 정렬은 콤마(,)로 구분.
        허용되지 않은 정렬 필드 및 방향은 무시합니다.
        형식: field:asc | field:desc
        허용 필드: createdAt,
        예: sort=-title:asc,createdAt:asc
          
     */
  sort?: string;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom400Code =
  (typeof JoinGameRoomControllerJoinGameRoom400Code)[keyof typeof JoinGameRoomControllerJoinGameRoom400Code];

export const JoinGameRoomControllerJoinGameRoom400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;
export type JoinGameRoomControllerJoinGameRoom400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom400Code;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom401Code =
  (typeof JoinGameRoomControllerJoinGameRoom401Code)[keyof typeof JoinGameRoomControllerJoinGameRoom401Code];

export const JoinGameRoomControllerJoinGameRoom401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;
export type JoinGameRoomControllerJoinGameRoom401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom401Code;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom404Code =
  (typeof JoinGameRoomControllerJoinGameRoom404Code)[keyof typeof JoinGameRoomControllerJoinGameRoom404Code];

export const JoinGameRoomControllerJoinGameRoom404Code = {
  GAME_ROOMNOT_FOUND: 'GAME_ROOM.NOT_FOUND',
} as const;
export type JoinGameRoomControllerJoinGameRoom404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom404Code;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom409Code =
  (typeof JoinGameRoomControllerJoinGameRoom409Code)[keyof typeof JoinGameRoomControllerJoinGameRoom409Code];

export const JoinGameRoomControllerJoinGameRoom409Code = {
  GAME_ROOM_MEMBERALREADY_EXISTS: 'GAME_ROOM_MEMBER.ALREADY_EXISTS',
  GAME_ROOM_MEMBERCAPACITY_EXCEEDED: 'GAME_ROOM_MEMBER.CAPACITY_EXCEEDED',
} as const;
export type JoinGameRoomControllerJoinGameRoom409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom409Code;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom500Code =
  (typeof JoinGameRoomControllerJoinGameRoom500Code)[keyof typeof JoinGameRoomControllerJoinGameRoom500Code];

export const JoinGameRoomControllerJoinGameRoom500Code = {
  ACCOUNTNOT_FOUND: 'ACCOUNT.NOT_FOUND',
} as const;
export type JoinGameRoomControllerJoinGameRoom500 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom500Code;
};
/**
 * error code
 */
export type LeaveGameRoomControllerLeaveGameRoom400Code =
  (typeof LeaveGameRoomControllerLeaveGameRoom400Code)[keyof typeof LeaveGameRoomControllerLeaveGameRoom400Code];

export const LeaveGameRoomControllerLeaveGameRoom400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;
export type LeaveGameRoomControllerLeaveGameRoom400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: LeaveGameRoomControllerLeaveGameRoom400Code;
};
/**
 * error code
 */
export type LeaveGameRoomControllerLeaveGameRoom403Code =
  (typeof LeaveGameRoomControllerLeaveGameRoom403Code)[keyof typeof LeaveGameRoomControllerLeaveGameRoom403Code];

export const LeaveGameRoomControllerLeaveGameRoom403Code = {
  GAME_ROOMACCESS_DENIED: 'GAME_ROOM.ACCESS_DENIED',
} as const;
export type LeaveGameRoomControllerLeaveGameRoom403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: LeaveGameRoomControllerLeaveGameRoom403Code;
};
/**
 * error code
 */
export type LeaveGameRoomControllerLeaveGameRoom404Code =
  (typeof LeaveGameRoomControllerLeaveGameRoom404Code)[keyof typeof LeaveGameRoomControllerLeaveGameRoom404Code];

export const LeaveGameRoomControllerLeaveGameRoom404Code = {
  GAME_ROOMNOT_FOUND: 'GAME_ROOM.NOT_FOUND',
  GAME_ROOM_MEMBERNOT_FOUND: 'GAME_ROOM_MEMBER.NOT_FOUND',
} as const;
export type LeaveGameRoomControllerLeaveGameRoom404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: LeaveGameRoomControllerLeaveGameRoom404Code;
};
/**
 * error code
 */
export type ListGameRoomMembersControllerListGameRoomMembers400Code =
  (typeof ListGameRoomMembersControllerListGameRoomMembers400Code)[keyof typeof ListGameRoomMembersControllerListGameRoomMembers400Code];

export const ListGameRoomMembersControllerListGameRoomMembers400Code = {
  COMMONREQUEST_VALIDATION_ERROR: 'COMMON.REQUEST_VALIDATION_ERROR',
} as const;
export type ListGameRoomMembersControllerListGameRoomMembers400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListGameRoomMembersControllerListGameRoomMembers400Code;
};
/**
 * error code
 */
export type ListGameRoomMembersControllerListGameRoomMembers401Code =
  (typeof ListGameRoomMembersControllerListGameRoomMembers401Code)[keyof typeof ListGameRoomMembersControllerListGameRoomMembers401Code];

export const ListGameRoomMembersControllerListGameRoomMembers401Code = {
  COMMONUNAUTHORIZED: 'COMMON.UNAUTHORIZED',
} as const;
export type ListGameRoomMembersControllerListGameRoomMembers401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListGameRoomMembersControllerListGameRoomMembers401Code;
};
/**
 * error code
 */
export type ListGameRoomMembersControllerListGameRoomMembers403Code =
  (typeof ListGameRoomMembersControllerListGameRoomMembers403Code)[keyof typeof ListGameRoomMembersControllerListGameRoomMembers403Code];

export const ListGameRoomMembersControllerListGameRoomMembers403Code = {
  GAME_ROOMACCESS_DENIED: 'GAME_ROOM.ACCESS_DENIED',
} as const;
export type ListGameRoomMembersControllerListGameRoomMembers403 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListGameRoomMembersControllerListGameRoomMembers403Code;
};
/**
 * error code
 */
export type ListGameRoomMembersControllerListGameRoomMembers404Code =
  (typeof ListGameRoomMembersControllerListGameRoomMembers404Code)[keyof typeof ListGameRoomMembersControllerListGameRoomMembers404Code];

export const ListGameRoomMembersControllerListGameRoomMembers404Code = {
  GAME_ROOMNOT_FOUND: 'GAME_ROOM.NOT_FOUND',
} as const;
export type ListGameRoomMembersControllerListGameRoomMembers404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: ListGameRoomMembersControllerListGameRoomMembers404Code;
};
