/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
export interface SignUpWithUsernameDto {
  username: string;
  password: string;
}
export interface AuthTokenDto {
  accessToken: string;
}
export interface SignInWithUsernameDto {
  username: string;
  password: string;
}
export interface CreateGameRoomDto {
  /**
   * 게임 방 제목
   * @minLength 1
   * @maxLength 50
   */
  title: string;
}
export type GameRoomDtoStatus =
  | 'waiting'
  | 'ready'
  | 'inProgress'
  | 'finished'
  | 'paused';
export interface GameRoomDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  hostId: string;
  status: GameRoomDtoStatus;
  title: string;
  maxPlayersCount: number;
}
/**
 * error code
 */
export type SignUpWithUsernameControllerSignUpWithUsername400Code =
  'COMMON.REQUEST_VALIDATION_ERROR';
export type SignUpWithUsernameControllerSignUpWithUsername400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignUpWithUsernameControllerSignUpWithUsername400Code;
};
/**
 * error code
 */
export type SignUpWithUsernameControllerSignUpWithUsername409Code =
  'ACCOUNT.USERNAME_ALREADY_OCCUPIED';
export type SignUpWithUsernameControllerSignUpWithUsername409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignUpWithUsernameControllerSignUpWithUsername409Code;
};
/**
 * error code
 */
export type SignInWithUsernameControllerSignInWithUsername400Code =
  'COMMON.REQUEST_VALIDATION_ERROR';
export type SignInWithUsernameControllerSignInWithUsername400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignInWithUsernameControllerSignInWithUsername400Code;
};
/**
 * error code
 */
export type SignInWithUsernameControllerSignInWithUsername401Code =
  'AUTH.SIGN_IN_INFO_NOT_MATCHED';
export type SignInWithUsernameControllerSignInWithUsername401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignInWithUsernameControllerSignInWithUsername401Code;
};
/**
 * error code
 */
export type CreateGameRoomControllerCreateGameRoom400Code =
  'COMMON.REQUEST_VALIDATION_ERROR';
export type CreateGameRoomControllerCreateGameRoom400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateGameRoomControllerCreateGameRoom400Code;
};
/**
 * error code
 */
export type CreateGameRoomControllerCreateGameRoom401Code =
  'COMMON.UNAUTHORIZED';
export type CreateGameRoomControllerCreateGameRoom401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateGameRoomControllerCreateGameRoom401Code;
};
