/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
export interface SignUpWithUsernameDto {
  username: string;
  password: string;
}
export interface AuthTokenDto {
  accessToken: string;
}
export interface SignInWithUsernameDto {
  username: string;
  password: string;
}
export interface CreateGameRoomDto {
  /**
   * 게임 방 제목
   * @minLength 1
   * @maxLength 50
   */
  title: string;
}
export type GameRoomDtoStatus =
  | 'waiting'
  | 'ready'
  | 'inProgress'
  | 'finished'
  | 'paused';
export interface GameRoomDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  hostId: string;
  status: GameRoomDtoStatus;
  title: string;
  maxMembersCount: number;
  currentMembersCount: number;
}
export type GameRoomMemberDtoRole = 'host' | 'player';
export interface GameRoomMemberDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
  gameRoomId: string;
  role: GameRoomMemberDtoRole;
}
export interface GameRoomCollectionDto {
  data: GameRoomDto[];
}
/**
 * error code
 */
export type SignUpWithUsernameControllerSignUpWithUsername400Code =
  'COMMON.REQUEST_VALIDATION_ERROR';
export type SignUpWithUsernameControllerSignUpWithUsername400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignUpWithUsernameControllerSignUpWithUsername400Code;
};
/**
 * error code
 */
export type SignUpWithUsernameControllerSignUpWithUsername409Code =
  'ACCOUNT.USERNAME_ALREADY_OCCUPIED';
export type SignUpWithUsernameControllerSignUpWithUsername409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignUpWithUsernameControllerSignUpWithUsername409Code;
};
/**
 * error code
 */
export type SignInWithUsernameControllerSignInWithUsername400Code =
  'COMMON.REQUEST_VALIDATION_ERROR';
export type SignInWithUsernameControllerSignInWithUsername400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignInWithUsernameControllerSignInWithUsername400Code;
};
/**
 * error code
 */
export type SignInWithUsernameControllerSignInWithUsername401Code =
  'AUTH.SIGN_IN_INFO_NOT_MATCHED';
export type SignInWithUsernameControllerSignInWithUsername401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: SignInWithUsernameControllerSignInWithUsername401Code;
};
/**
 * error code
 */
export type CreateGameRoomControllerCreateGameRoom400Code =
  'COMMON.REQUEST_VALIDATION_ERROR';
export type CreateGameRoomControllerCreateGameRoom400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateGameRoomControllerCreateGameRoom400Code;
};
/**
 * error code
 */
export type CreateGameRoomControllerCreateGameRoom401Code =
  'COMMON.UNAUTHORIZED';
export type CreateGameRoomControllerCreateGameRoom401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: CreateGameRoomControllerCreateGameRoom401Code;
};
export type ListGameRoomsControllerListGameRoomsParams = {
  /**
     *
        정렬 쿼리. 다중 정렬은 콤마(,)로 구분.
        허용되지 않은 정렬 필드 및 방향은 무시합니다.
        형식: field:asc | field:desc
        허용 필드: createdAt,
        예: sort=-title:asc,createdAt:asc
          
     */
  sort?: string;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom400Code =
  'COMMON.REQUEST_VALIDATION_ERROR';
export type JoinGameRoomControllerJoinGameRoom400 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom400Code;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom401Code = 'COMMON.UNAUTHORIZED';
export type JoinGameRoomControllerJoinGameRoom401 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom401Code;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom404Code = 'GAME_ROOM.NOT_FOUND';
export type JoinGameRoomControllerJoinGameRoom404 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom404Code;
};
/**
 * error code
 */
export type JoinGameRoomControllerJoinGameRoom409Code =
  | 'GAME_ROOM_MEMBER.ALREADY_EXISTS'
  | 'GAME_ROOM_MEMBER.CAPACITY_EXCEEDED';
export type JoinGameRoomControllerJoinGameRoom409 = {
  /** http status code */
  statusCode?: number;
  /** error message */
  message?: string;
  /** error code */
  code?: JoinGameRoomControllerJoinGameRoom409Code;
};
