/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend API
 * OpenAPI spec version: 0.1
 */
import type {
  AuthTokenDto,
  CreateGameRoomDto,
  GameRoomCollectionDto,
  GameRoomDto,
  GameRoomMemberDto,
  ListGameRoomsControllerListGameRoomsParams,
  SignInWithUsernameDto,
  SignUpWithUsernameDto,
} from './quizzesGameIoBackend.schemas';

import { orvalInstance } from '../../../shared/service/api/client/index';

/**
 * @summary username 기반 회원가입
 */
export const signUpWithUsernameControllerSignUpWithUsername = (
  signUpWithUsernameDto: SignUpWithUsernameDto
) => {
  return orvalInstance<AuthTokenDto>({
    url: `/auth/sign-up/username`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: signUpWithUsernameDto,
  });
};

/**
 * @summary username 기반 로그인
 */
export const signInWithUsernameControllerSignInWithUsername = (
  signInWithUsernameDto: SignInWithUsernameDto
) => {
  return orvalInstance<AuthTokenDto>({
    url: `/auth/sign-in/username`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: signInWithUsernameDto,
  });
};

/**
 * @summary 게임 방 생성
 */
export const createGameRoomControllerCreateGameRoom = (
  createGameRoomDto: CreateGameRoomDto
) => {
  return orvalInstance<GameRoomDto>({
    url: `/game-rooms`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createGameRoomDto,
  });
};

/**
 * @summary 게임방 목록 조회
 */
export const listGameRoomsControllerListGameRooms = (
  params?: ListGameRoomsControllerListGameRoomsParams
) => {
  return orvalInstance<GameRoomCollectionDto>({
    url: `/game-rooms`,
    method: 'GET',
    params,
  });
};

/**
 * @summary 게임 방 입장
 */
export const joinGameRoomControllerJoinGameRoom = (gameRoomId: string) => {
  return orvalInstance<GameRoomMemberDto>({
    url: `/game-room/${gameRoomId}/members`,
    method: 'POST',
  });
};

export type SignUpWithUsernameControllerSignUpWithUsernameResult = NonNullable<
  Awaited<ReturnType<typeof signUpWithUsernameControllerSignUpWithUsername>>
>;
export type SignInWithUsernameControllerSignInWithUsernameResult = NonNullable<
  Awaited<ReturnType<typeof signInWithUsernameControllerSignInWithUsername>>
>;
export type CreateGameRoomControllerCreateGameRoomResult = NonNullable<
  Awaited<ReturnType<typeof createGameRoomControllerCreateGameRoom>>
>;
export type ListGameRoomsControllerListGameRoomsResult = NonNullable<
  Awaited<ReturnType<typeof listGameRoomsControllerListGameRooms>>
>;
export type JoinGameRoomControllerJoinGameRoomResult = NonNullable<
  Awaited<ReturnType<typeof joinGameRoomControllerJoinGameRoom>>
>;
