---
name: 🐛 버그 신고
about: 버그를 신고할 때 사용하세요
title: '[BUG] '
labels: ['bug']
assignees: ''
---

## 🐛 버그 설명
<!-- 어떤 버그가 발생했는지 명확하고 간결하게 설명해주세요 -->

## 🔄 재현 단계
1. '...'로 이동
2. '...'을 클릭
3. '...'까지 스크롤
4. 오류 확인

## 🎯 예상 동작
<!-- 원래 어떻게 동작해야 하는지 설명해주세요 -->

## 📱 실제 동작
<!-- 실제로 어떤 일이 일어났는지 설명해주세요 -->

## 📸 스크린샷
<!-- 가능하면 스크린샷을 추가해주세요 -->

## 🖥️ 환경 정보
- OS: [예: iOS, Android, Windows, macOS]
- 브라우저: [예: Chrome, Safari, Firefox]
- 버전: [예: 22]
- 디바이스: [예: iPhone 12, Samsung Galaxy]

## 📋 추가 정보
<!-- 버그와 관련된 추가 정보가 있다면 작성해주세요 -->

## ⚡ 우선순위
- [ ] 🔴 높음 (서비스 중단)
- [ ] 🟡 보통 (기능 문제)
- [ ] 🟢 낮음 (사소한 문제)
