---
name: ✨ 기능 요청
about: 새로운 기능을 요청할 때 사용하세요
title: '[FEATURE] '
labels: ['feature']
assignees: ''
---

## 🎯 기능 설명
<!-- 어떤 기능이 필요한지 명확하고 간결하게 설명해주세요 -->

## 💡 해결하고자 하는 문제
<!-- 이 기능이 어떤 문제를 해결하는지 설명해주세요 -->

## 🔧 제안하는 해결책
<!-- 어떻게 구현하면 좋을지 설명해주세요 -->

## 📋 상세 요구사항
<!-- 기능에 대한 구체적인 요구사항들을 작성해주세요 -->
- [ ] 요구사항 1
- [ ] 요구사항 2
- [ ] 요구사항 3

## 🎨 UI/UX 고려사항
<!-- UI나 사용자 경험과 관련된 고려사항이 있다면 작성해주세요 -->

## 📱 지원 플랫폼
- [ ] 🖥️ 데스크톱
- [ ] 📱 모바일
- [ ] 🔄 반응형

## 🔄 대안 방안
<!-- 다른 해결 방법이 있다면 설명해주세요 -->

## 📚 참고 자료
<!-- 참고할 만한 링크나 자료가 있다면 첨부해주세요 -->

## ⚡ 우선순위
- [ ] 🔴 높음 (핵심 기능)
- [ ] 🟡 보통 (중요 기능)
- [ ] 🟢 낮음 (개선 사항)

## 📊 성공 기준
<!-- 이 기능이 성공적으로 구현되었다고 판단할 수 있는 기준을 작성해주세요 -->
