/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * quizzes-game-io-backend
 * The Quizzes Game IO Backend Async API
 * OpenAPI spec version: 0.1
 */
export type Payload = AccountEnteredSocketEvent;
export interface AccountEnteredSocketEventBodyAccount {
  id: string;
  enteredAt: string;
}
export interface AccountEnteredSocketEventBody {
  account: AccountEnteredSocketEventBodyAccount;
  currentActiveAccountsCount: number;
}
export type AccountEnteredSocketEventMeta = {
  [key: string]: unknown;
};
export interface AccountEnteredSocketEvent {
  eventName: string;
  timestamp: string;
  body: AccountEnteredSocketEventBody;
  meta: AccountEnteredSocketEventMeta;
}
