/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyIndexRouteImport } from './routes/lobby/index'
import { Route as RoomRoomIdIndexRouteImport } from './routes/room/$roomId/index'
import { Route as RoomRoomIdInPlayRouteImport } from './routes/room/$roomId/in-play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyIndexRoute = LobbyIndexRouteImport.update({
  id: '/lobby/',
  path: '/lobby/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdIndexRoute = RoomRoomIdIndexRouteImport.update({
  id: '/room/$roomId/',
  path: '/room/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdInPlayRoute = RoomRoomIdInPlayRouteImport.update({
  id: '/room/$roomId/in-play',
  path: '/room/$roomId/in-play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/room/$roomId/in-play': typeof RoomRoomIdInPlayRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/room/$roomId/in-play': typeof RoomRoomIdInPlayRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lobby/': typeof LobbyIndexRoute
  '/room/$roomId/in-play': typeof RoomRoomIdInPlayRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lobby' | '/room/$roomId/in-play' | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lobby' | '/room/$roomId/in-play' | '/room/$roomId'
  id: '__root__' | '/' | '/lobby/' | '/room/$roomId/in-play' | '/room/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LobbyIndexRoute: typeof LobbyIndexRoute
  RoomRoomIdInPlayRoute: typeof RoomRoomIdInPlayRoute
  RoomRoomIdIndexRoute: typeof RoomRoomIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/': {
      id: '/lobby/'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/': {
      id: '/room/$roomId/'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/in-play': {
      id: '/room/$roomId/in-play'
      path: '/room/$roomId/in-play'
      fullPath: '/room/$roomId/in-play'
      preLoaderRoute: typeof RoomRoomIdInPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LobbyIndexRoute: LobbyIndexRoute,
  RoomRoomIdInPlayRoute: RoomRoomIdInPlayRoute,
  RoomRoomIdIndexRoute: RoomRoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
